name: Run Cypress Test

on:
  push:
    branches:
      - main

jobs:
    cypress-runner:
        runs-on: ubuntu-latest

        steps:
        - name: Intialize NPM
          uses: actions/checkout@v4
        # - run: |
        #       ls -la list all items in the current directory
        #       find . -type f lists folder and subfolders and files in the current directory

        - name: Run Cypress
          uses: cypress-io/github-action@v6

        - name: Upload Report
          uses: actions/upload-artifact@v4
          with:
              name: reports
              path: |
                  cypress/reports/